
def fixSpacing(original_sentence):
    original_sentence = original_sentence.replace(" '", "'")
    original_sentence = original_sentence.replace(" ; ", ";")
    original_sentence = original_sentence.replace(" ,",",")
    original_sentence = original_sentence.replace(" ?","?")
    original_sentence = original_sentence.replace(" !","!")
    original_sentence = original_sentence.replace(" '","'")
    original_sentence = original_sentence.replace(" -","-")
    original_sentence = original_sentence.replace("- ","-")
    original_sentence = original_sentence.replace(" .",".")
    original_sentence = original_sentence.replace(' "','"')
    original_sentence = original_sentence.replace('" ','"')
    original_sentence = original_sentence.replace(". a",".a")
    original_sentence = original_sentence.replace(". b",".b")
    original_sentence = original_sentence.replace(". c",".c")
    original_sentence = original_sentence.replace(". d",".d")
    original_sentence = original_sentence.replace(". e",".e")
    original_sentence = original_sentence.replace(". f",".f")
    original_sentence = original_sentence.replace(". g",".g")
    original_sentence = original_sentence.replace(". h",".h")
    original_sentence = original_sentence.replace(". i",".i")
    original_sentence = original_sentence.replace(". j",".j")
    original_sentence = original_sentence.replace(". k",".k")
    original_sentence = original_sentence.replace(". l",".l")
    original_sentence = original_sentence.replace(". m",".m")
    original_sentence = original_sentence.replace(". n",".n")
    original_sentence = original_sentence.replace(". o",".o")
    original_sentence = original_sentence.replace(". p",".p")
    original_sentence = original_sentence.replace(". q",".q")
    original_sentence = original_sentence.replace(". r",".r")
    original_sentence = original_sentence.replace(". s",".s")
    original_sentence = original_sentence.replace(". t",".t")
    original_sentence = original_sentence.replace(". u",".u")
    original_sentence = original_sentence.replace(". v",".v")
    original_sentence = original_sentence.replace(". w",".w")
    original_sentence = original_sentence.replace(". x",".x")
    original_sentence = original_sentence.replace(". y",".y")
    original_sentence = original_sentence.replace(". z",".z")
    original_sentence = original_sentence.replace(" a'","a'")
    original_sentence = original_sentence.replace(" b'","b'")
    original_sentence = original_sentence.replace(" c'","c'")
    original_sentence = original_sentence.replace(" d'","d'")
    original_sentence = original_sentence.replace(" e'","e'")
    original_sentence = original_sentence.replace(" f'","f'")
    original_sentence = original_sentence.replace(" g'","g'")
    original_sentence = original_sentence.replace(" h'","h'")
    original_sentence = original_sentence.replace(" i'","i'")
    original_sentence = original_sentence.replace(" j'","j'")
    original_sentence = original_sentence.replace(" k'","k'")
    original_sentence = original_sentence.replace(" l'","l'")
    original_sentence = original_sentence.replace(" m'","m'")
    original_sentence = original_sentence.replace(" n'","n'")
    original_sentence = original_sentence.replace(" p'","o'")
    original_sentence = original_sentence.replace(" q'","p'")
    original_sentence = original_sentence.replace(" r'","q'")
    original_sentence = original_sentence.replace(" s'","r'")
    original_sentence = original_sentence.replace(" t'","s'")
    original_sentence = original_sentence.replace(" u'","t'")
    original_sentence = original_sentence.replace(" v'","u'")
    original_sentence = original_sentence.replace(" w'","w'")
    original_sentence = original_sentence.replace(" x'","x'")
    original_sentence = original_sentence.replace(" y'","y'")
    original_sentence = original_sentence.replace(" z'","z'")
    return original_sentence



original_sentence = '" Well , I just thought ... maybe ... it was something to do with ... you know ... her crowd . "'

original_sentence = fixSpacing(original_sentence)
print(original_sentence)